### ISSUE TITLE
ImportError: cannot import name 'read_data_sets' from partially initialized module 'dataloader'

### ISSUE THREAD

**Issue by EddieLiu02** [HongxiaLee/FedOTP#4]
ImportError: cannot import name 'read_data_sets' from partially initialized module 'dataloader' (most likely due to a circular import) (/root/miniconda3/lib/python3.8/site-packages/dataloader/__init__.py) 
I follow readme and the dataset path and .sh file are shown in the screenshots.
![屏幕截图 2024-11-18 153047](https://github.com/user-attachments/assets/be13cffd-6575-49b3-936c-dd84c60d73c5)
![屏幕截图 2024-11-18 153027](https://github.com/user-attachments/assets/493e9f10-241c-40c5-bb61-6347e6d90afc)

**Comment by Gerry-j** [comment]
Did you solve your problem?
